//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public Deliveries()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int DeliveryID { get; set; }
        public string DeliveryName { get; set; }
        public decimal DeliveryCost { get; set; }
        public Nullable<int> EstimatedDays { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
