//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public Discounts()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int DiscountID { get; set; }
        public string DiscountName { get; set; }
        public decimal Percentage { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
