//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Warehouses = new HashSet<Warehouses>();
        }
    
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
        public int PositionID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Warehouses> Warehouses { get; set; }
    }
}
