//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufactures
    {
        public Manufactures()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ManufacturyID { get; set; }
        public string ManufacturyName { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
