//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int DeliveryID { get; set; }
        public int WarehouseID { get; set; }
        public int PaymentTypeID { get; set; }
        public int PaymentStatusID { get; set; }
        public int OrderStatusID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> DiscountApplied { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Deliveries Deliveries { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual OrdersStatus OrdersStatus { get; set; }
        public virtual PaymentsStatus PaymentsStatus { get; set; }
        public virtual PaymentsType PaymentsType { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
