//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsStatus
    {
        public PaymentsStatus()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PaymentStatusID { get; set; }
        public string PaymentStatusName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
