//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Clients = new HashSet<Clients>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual Role Role { get; set; }
    }
}
