//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmurStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouses
    {
        public Warehouses()
        {
            this.Orders = new HashSet<Orders>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public string Address { get; set; }
        public int EmployeeID { get; set; }
        public string Phone { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
